name: audio_trimmer
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # state management
  flutter_bloc: ^8.1.6
  # dependency Injection
  get_it: ^7.7.0
  # page routing
  go_router: ^14.2.7
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  file_picker: ^8.1.2
  just_audio: ^0.9.40
  easy_audio_trimmer: ^1.0.2+4
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
